# PRINT
print("===== START PRINT =====");
print(10);
print(true);
print("hello world");
print(10 + 5);                  # 15
print(10 - 2);                  # 8
print(10 * 4);                  # 40
print(10 / 2);                  # 5
print(10 * 4 / 2 + 1);          # 21
print(10 % 3);                  # 1
print(!false);
print(-8);                      # -8 (bisa dalam versi masih unsigned)
print(!!!false);                # 1
print(!!-8 * 3);                # 3
print("===== END PRINT =====");