# TYPEOF
print("===== START TYPEOF USE =====");
var tipeInt = 10;
print(typeof(tipeInt));         # 0 (int)


tipeInt = "jadi str";
print(typeof(tipeInt));         # 1 (string)

tipeInt = true;
print(typeof(tipeInt));         # 2 (bool)



# USE
use std.math

print(math.abs(-79));                  # 79
print(math.min(8, 7));                 # 7
print(math.max(8, 7));                 # 8
print("===== END TYPEOF USE =====");