# ASSIGNMENT
print("===== START ASSIGN =====");
var assign1 = "hemm";
print(assign1);                 # hemm

var assign2;
print(assign2);                 # 0
assign2 = true;
print(assign2);                 # 1
assign2 = 10;
print(assign2);                 # 10
assign2 = "wello";
print(assign2);                 # wello
assign2 = assign1;
print(assign2);                 # hemm

var assignDecl = assign1;
print(assignDecl);              # hemm
assign1 =  "ganti assign1";
print(assign1);                 # ganti assign
print(assignDecl);              # hemm

# print(10.5);
# var float = 10.5 + 2.3;
print("===== END ASSIGN =====");